### ISSUE TITLE
Error: The assembly Cake.ArgumentHelpers is referencing an older version of Cake.Core

### ISSUE THREAD

**Issue by VictorioBerra** [cake-contrib/Cake.ArgumentHelpers#3]
```
Error: The assembly 'Cake.ArgumentHelpers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
is referencing an older version of Cake.Core (0.22.2).
This assembly need to reference at least Cake.Core version 0.26.0.
```

Please consider targeting the latest version of Cake.

**Comment by igloo15** [comment]
As much as its nice to keep cake files uncluttered with various methods and what not just adding this bit of code into your cake script will do the same thing this library is doing. I hope that this library is updated but if you want to get around the skip verification thing just use the below code for now.

Just insert it in your cake file outside of a task.

```csharp
public string ArgumentOrEnvironmentVariable(string name, string envPrefix, string defaultValue)
{
    return Argument<string>(name, EnvironmentVariable(envPrefix + name)) ?? defaultValue;
}
```

**Comment by mike-echo-oscar-whiskey** [comment]
It looks like this repo is dead.

**Comment by VictorioBerra** [comment]
@youfoundkris Probably a good thing. CAKE has been slowly adding this libraries features over and now you can combine them to essentially do what this library does. You can start your own and share it via your companies nuget feed.
