### ISSUE TITLE
NetStandard output

### ISSUE THREAD

**Issue by zkosior** [cake-contrib/Cake.ArgumentHelpers#6]
I'm getting (Error: Failed to install addin 'Cake.ArgumentHelpers'.) when running cake as dotnet local tool (dotnet tool run dotnet-cake) with powershell bootstrapper from [here](https://andrewlock.net/simplifying-the-cake-global-tool-bootstrapper-scripts-in-netcore3-with-local-tools/)
My guess is that it's because there is no netstandard output.

**Comment by cskita** [comment]
Hi!

I've got the same issue, this will be solved?

**Comment by augustoproiete** [comment]
@cskita Would you be interested in sending a PR to update the project to target `netstandard2.0` and Cake v1.0?

**Comment by augustoproiete** [comment]
:tada: The changes implemented in response to this issue shipped with **Cake.ArgumentHelpers v1.0.0**

The release is available on:

- :rocket: [GitHub Release](https://github.com/cake-contrib/Cake.ArgumentHelpers/releases/tag/v1.0.0)
- :package: [NuGet Package](https://www.nuget.org/packages/Cake.ArgumentHelpers/1.0.0)
